// Mock data representing courses you might get from an API
export const MockCourse = [
  {
    id: 1,
    title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
    category: 'Web Development',
    level: 'Beginner',
    price: 49.99,
    durationInHours: 40.5,
    rating: 4.6,
    enrollmentCount: 250000,
    instructor: 'Maximilian Schwarzmüller',
    imageUrl: 'https://i.imgur.com/y4tA32e.jpeg',
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: 2,
    title: 'The Complete 2023 Web Development Bootcamp',
    category: 'Web Development',
    level: 'Beginner',
    price: 59.99,
    durationInHours: 55,
    rating: 4.7,
    enrollmentCount: 300000,
    instructor: 'Dr. Angela Yu',
    imageUrl: 'https://i.imgur.com/1trg4r2.jpeg',
    createdAt: '2023-02-01T12:00:00Z',
  },
  {
    id: 3,
    title: 'Python for Data Science and Machine Learning Bootcamp',
    category: 'Data Science',
    level: 'Intermediate',
    price: 89.99,
    durationInHours: 25,
    rating: 4.6,
    enrollmentCount: 150000,
    instructor: 'Jose Portilla',
    imageUrl: 'https://i.imgur.com/eBf2yUQ.jpeg',
    createdAt: '2023-03-10T09:00:00Z',
  },
  {
    id: 4,
    title: 'The Ultimate Digital Marketing Course 2023',
    category: 'Marketing',
    level: 'Beginner',
    price: 0, // Free course
    durationInHours: 11.5,
    rating: 4.5,
    enrollmentCount: 95000,
    instructor: 'Joshua George',
    imageUrl: 'https://i.imgur.com/wVj2a2h.jpeg',
    createdAt: '2023-04-05T14:30:00Z',
  },
  {
    id: 5,
    title: 'Advanced CSS and Sass: Flexbox, Grid, Animations and More!',
    category: 'Web Development',
    level: 'Advanced',
    price: 29.99,
    durationInHours: 28,
    rating: 4.8,
    enrollmentCount: 120000,
    instructor: 'Jonas Schmedtmann',
    imageUrl: 'https://i.imgur.com/dK4F6oF.jpeg',
    createdAt: '2022-12-20T11:00:00Z',
  },
   {
    id: 6,
    title: 'Machine Learning A-Z™: AI, Python & R',
    category: 'Data Science',
    level: 'Advanced',
    price: 99.99,
    durationInHours: 44,
    rating: 4.5,
    enrollmentCount: 180000,
    instructor: 'Kirill Eremenko',
    imageUrl: 'https://i.imgur.com/q2N2m5I.jpeg',
    createdAt: '2023-05-01T16:00:00Z',
  },
  {
    id: 7,
    title: 'Graphic Design Masterclass - Learn GREAT Design',
    category: 'Design',
    level: 'Beginner',
    price: 39.99,
    durationInHours: 35,
    rating: 4.7,
    enrollmentCount: 80000,
    instructor: 'Lindsay Marsh',
    imageUrl: 'https://i.imgur.com/b9L4YwB.jpeg',
    createdAt: '2023-02-18T18:00:00Z',
  },
   {
    id: 8,
    title: 'The Complete Financial Analyst Course 2023',
    category: 'Business',
    level: 'Intermediate',
    price: 79.99,
    durationInHours: 22.5,
    rating: 4.5,
    enrollmentCount: 110000,
    instructor: 'Chris Haroun',
    imageUrl: 'https://i.imgur.com/gT7hmsf.jpeg',
    createdAt: '2023-03-25T20:00:00Z',
  },
  // Add more courses as needed to test pagination
];
export default MockCourse;